# Generated by Django 2.1.7 on 2019-03-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_doc_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='doc_file',
        ),
    ]
