# Generated by Django 2.1.7 on 2019-03-14 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190314_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='scripts/pdfs/'),
            preserve_default=False,
        ),
    ]
