# Generated by Django 2.1.7 on 2019-03-14 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf',
        ),
        migrations.AddField(
            model_name='post',
            name='doc_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/site_docs/'),
            preserve_default=False,
        ),
    ]
