# Generated by Django 2.1.7 on 2019-03-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190314_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default=('anthem', 'classical', 'highlife', 'hymns'), max_length=50, null=True),
        ),
    ]
