# Generated by Django 2.1.7 on 2019-03-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_price',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('Anthem', 'ANTHEM'), ('Classical', 'CLASSICAL'), ('Highlife', 'HIGHLIFE'), ('Hymn', 'HYMN')], default='Anthem', max_length=30, null=True),
        ),
    ]
