# Generated by Django 2.1.7 on 2019-03-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190324_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_price',
            field=models.TextField(default='$0.00', null=True),
        ),
    ]
