# Generated by Django 2.1.7 on 2019-03-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190324_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_price',
            field=models.TextField(default='Ghȼ0.00', null=True),
        ),
    ]
