# Generated by Django 2.1.7 on 2019-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190324_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_price',
            field=models.IntegerField(default='0.00', null=True),
        ),
    ]
