# Generated by Django 2.1.7 on 2019-03-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190325_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_price',
            field=models.CharField(choices=[('Ant', '0.00')], default='Ant', max_length=30, null=True),
        ),
    ]
